site_name: GEML
repo_url: https://github.com/Cynerd/geml.git
site_description: General embedded macro language
copyright: GNU General Public License, version 2.0
pages:
- Home: index.md
- Syntax: syntax.md
- Built-in commands: builtin_commands.md
- Evaluation process: evaluation.md
- Modules creation: module_creation.md
theme: readthedocs

site_dir: html
